"""Shared, Glyphs-independent helpers for Glyph Note."""

from .core import (  # noqa: F401
    LAYER_NOTE_KEY,
    LOCKED_KEY,
    MASTER_NOTES_KEY,
    PLACEHOLDER_EMPTY_NOTE,
    PLACEHOLDER_EMPTY_NOTES,
    PLACEHOLDER_MULTIPLE,
    PLACEHOLDER_NO_SELECTION,
    PLUGIN_ID,
    SHOW_BADGES_DEFAULTS_KEY,
    GlyphNoteState,
    SelectionDisplay,
    apply_lock_to_states,
    apply_note_to_states,
    clean_note,
    clear_active_master_note,
    clear_all_notes,
    empty_state,
    get_display_note,
    get_master_note,
    has_any_note,
    has_visible_note,
    is_locked,
    layer_has_note,
    native_note,
    read_glyph_state,
    selection_display,
    set_display_note,
    set_locked,
    write_glyph_state,
)
